- name: variables
  hosts: localhost
  vars:
    Course: "Terraform"
    Trainer: 'Siva'
    Duration: "15hrs"

  become: no
  tasks:
  - name: Variable declaration
    ansible.builtin.debug:
      msg: "Ply level only: Hi,we are learning {{Course}} from {{Trainer}},duration is {{Duration}}"