- name: variables
  hosts: localhost
  vars:
    Course: "Terraform"
    Trainer: 'Siva'
    Duration: "15hrs"
  become: no
  tasks:
  - name: Variable declaration
    vars:
      Course: "DevOps"    
    ansible.builtin.debug:
      msg: "Hi Override task level,we are learning {{Course}} from {{Trainer}},duration is {{Duration}}"

  - name: Variable declaration
    ansible.builtin.debug:
      msg: "Hi Inheritance play level,we are learning {{Course}} from {{Trainer}},duration is {{Duration}}"      