- name: variables from play level
  hosts: localhost
  vars:
    Course: "Terraform"
    Trainer: 'Siva'
    Duration: "15hrs"
  become: no
  tasks:
  - name: Variable declaration from task level
    vars:
      Course: "DevOps"    
    ansible.builtin.debug:
      msg: "Hi task level2:  Override ,we are learning {{Course}} from {{Trainer}},duration is {{Duration}}"

  - name: Variable declaration
    ansible.builtin.debug:
      msg: "Hi Play level2: Inheritance ,we are learning {{Course}} from {{Trainer}},duration is {{Duration}}"      