- name: var from prompt
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: Please enter user name
    private: false
  - name: PASSWORD
    prompt: Please enter password
    private: true  

  tasks:
  - name: vr from fi
    ansible.builtin.debug:
      msg: "Prompt: username:{{USERNAME}},password:{{PASSWORD}}"