- name: condition check
  hosts: localhost
  become: yes 
  tasks:
  - name: check user exists or not
    ansible.builtin.command: id expense
    register: USER
    ignore_errors: true

  - name: check user info why failing
    ansible.builtin.debug:
      msg: "Failed msg:{{USER}}"

  - name: check user fails
    ansible.builtin.command: useradd expense
      when: USER.rc != 0
      
    
  - name: 
    ansible.builtin.debug:
      msg: Hello